import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {PlayerProvider} from "@/context/player-provider";
import {GameProvider} from "@/context/game-provider";
import React from "react";
import {ActionProvider} from "@/context/action-provider";
import {ChoiceProvider} from "@/context/choice-provider";
import {VoteProvider} from "@/context/vote-provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Cursed Village",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <PlayerProvider>
            <GameProvider>
                <ChoiceProvider>
                    <VoteProvider>
                        <ActionProvider>
                            {children}
                        </ActionProvider>
                    </VoteProvider>
                </ChoiceProvider>
            </GameProvider>
        </PlayerProvider>
        </body>
        </html>
    );
}
