import type {Metadata} from "next";
import {Montserrat} from "next/font/google";
import "./globals.css";
import {PlayerProvider} from "@/context/player-provider";
import {GameProvider} from "@/context/game-provider";
import React from "react";
import {ActionProvider} from "@/context/action-provider";
import {ChoiceProvider} from "@/context/choice-provider";
import {VoteProvider} from "@/context/vote-provider";

const montserrat = Montserrat({
    subsets: ['latin'],
    weight: ['400', '700'], // Choisis les graisses dont tu as besoin
    variable: '--font-montserrat', // Optionnel pour utiliser en CSS
})

export const metadata: Metadata = {
    title: "Cursed Village",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${montserrat.className} antialiased dark`}>
        <PlayerProvider>
            <GameProvider>
                <ChoiceProvider>
                    <VoteProvider>
                        <ActionProvider>
                            {children}
                        </ActionProvider>
                    </VoteProvider>
                </ChoiceProvider>
            </GameProvider>
        </PlayerProvider>
        </body>
        </html>
    );
}
